name: Database backup

on:
  schedule:
    - cron: '0 4,10,16 * * *'  # 每天的4点、10点和16点执行一次（格林尼治）
  workflow_dispatch:  # 允许手动触发

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'  

    - name: Run script
      run: node workflow.js