name: Database backup

on:
  schedule:
    - cron: '0 4,10,16 * * *'  # 每天的4点、10点和16点执行一次（格林尼治）
  workflow_dispatch:  # 允许手动触发

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.15.0'  

    - name: Install sqlite3 module
      run: | 
        npm install sqlite3

    - name: Run script
      env:
        USERNAME: ${{ secrets.DB_USERNAME }}
        PASSWORD: ${{ secrets.DB_PASSWORD }}
      run: node workflow.js
